"""Add indexes

Revision ID: 0f9e730b2dac
Revises: 3747d5c65885
Create Date: 2026-08-10 21:24:25.114281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9e730b2dac'
down_revision = '3747d5c65885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UpdatedAt', sa.DateTime(), nullable=True))
        batch_op.alter_column('Title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('OwnerId',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_Notes_CreatedAt'), ['CreatedAt'], unique=False)
        batch_op.create_index(batch_op.f('ix_Notes_OwnerId'), ['OwnerId'], unique=False)
        batch_op.create_index(batch_op.f('ix_Notes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Notes_id'))
        batch_op.drop_index(batch_op.f('ix_Notes_OwnerId'))
        batch_op.drop_index(batch_op.f('ix_Notes_CreatedAt'))
        batch_op.alter_column('OwnerId',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('UpdatedAt')

    # ### end Alembic commands ###
