"""introduce dashboard table

Revision ID: 2eed4c7932ec
Revises: 32d7a3f5817b
Create Date: 2026-08-11 19:44:23.852874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eed4c7932ec'
down_revision = '32d7a3f5817b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dashboards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Dashboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Dashboards_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_Dashboards_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_Notes_dashboard_id'), ['dashboard_id'], unique=False)
        batch_op.create_foreign_key(None, 'Dashboards', ['dashboard_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Notes_dashboard_id'))
        batch_op.drop_column('dashboard_id')

    with op.batch_alter_table('Dashboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Dashboards_owner_id'))
        batch_op.drop_index(batch_op.f('ix_Dashboards_created_at'))

    op.drop_table('Dashboards')
    # ### end Alembic commands ###
