"""Add indexes to user

Revision ID: 32d7a3f5817b
Revises: f1db3866c2b2
Create Date: 2026-08-10 21:46:49.421552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d7a3f5817b'
down_revision = 'f1db3866c2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Notes_id'))

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Users_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_Users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_email'))
        batch_op.create_unique_constraint(batch_op.f('Users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Notes_id'), ['id'], unique=False)

    # ### end Alembic commands ###
