"""describe the schema change

Revision ID: 3747d5c65885
Revises: 66447ec256d8
Create Date: 2026-08-10 21:16:46.333994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3747d5c65885'
down_revision = '66447ec256d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('OwnerId', sa.Integer(), nullable=True))
        batch_op.alter_column('Content',
               existing_type=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'Users', ['OwnerId'], ['id'])
        batch_op.drop_column('IsList')
        batch_op.drop_column('NoteId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NoteId', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('IsList', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('Content',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(postgresql.JSON(astext_type=sa.Text())),
               existing_nullable=True)
        batch_op.drop_column('OwnerId')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
