"""Add email_verified column to Users

Revision ID: 9cf7e98b4836
Revises: e8f4c2a91b07
Create Date: 2026-08-21 20:33:38.103361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf7e98b4836'
down_revision = 'e8f4c2a91b07'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("Users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "email_verified",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
