"""add unique constraint on dashboard owner_id and name

Revision ID: c69b584148cc
Revises: d1490a65be97
Create Date: 2026-08-14 15:25:50.611740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69b584148cc'
down_revision = 'd1490a65be97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dashboards', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_dashboards_owner_id_name', ['owner_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dashboards', schema=None) as batch_op:
        batch_op.drop_constraint('uq_dashboards_owner_id_name', type_='unique')

    # ### end Alembic commands ###
