"""edit note content from plain text to json

Revision ID: c73a3a5335c6
Revises: c69b584148cc
Create Date: 2026-08-15 12:26:28.131053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73a3a5335c6'
down_revision = 'c69b584148cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_json', sa.Text(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('content_json')

    # ### end Alembic commands ###
