"""add default value to dashboard model


Revision ID: d1490a65be97
Revises: 2eed4c7932ec
Create Date: 2026-08-11 20:39:22.490267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1490a65be97'
down_revision = '2eed4c7932ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dashboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dashboards', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
