"""Add indexes

Revision ID: f1db3866c2b2
Revises: 0f9e730b2dac
Create Date: 2026-08-10 21:37:44.962835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1db3866c2b2'
down_revision = '0f9e730b2dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_Notes_CreatedAt'))
        batch_op.drop_index(batch_op.f('ix_Notes_OwnerId'))
        batch_op.create_index(batch_op.f('ix_Notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_Notes_owner_id'), ['owner_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('Notes_OwnerId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['owner_id'], ['id'])
        batch_op.drop_column('UpdatedAt')
        batch_op.drop_column('CreatedAt')
        batch_op.drop_column('OwnerId')
        batch_op.drop_column('Title')
        batch_op.drop_column('Content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Title', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('OwnerId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('CreatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('UpdatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Notes_OwnerId_fkey'), 'Users', ['OwnerId'], ['id'])
        batch_op.drop_index(batch_op.f('ix_Notes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_Notes_created_at'))
        batch_op.create_index(batch_op.f('ix_Notes_OwnerId'), ['OwnerId'], unique=False)
        batch_op.create_index(batch_op.f('ix_Notes_CreatedAt'), ['CreatedAt'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('owner_id')
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
